#!/usr/bin/env python3


# make sure PyPSUcurvetrace is on the Python search path, for example:
# export PYTHONPATH=$PYTHONPATH:$HOME/PyPSUcurvetrace/


import argparse
import numpy as np

from lib.read_datafile import read_datafile

# input arguments:
parser = argparse.ArgumentParser(description='refrep_proc: process refrep data.')
parser.add_argument('datafiles', nargs='+', help='Names (and paths) of PyPSUcurvetrace data files. A list of multiple files can be used for an overlay plot. Files can also be specified using wildcards.')
args = parser.parse_args()
datafiles = args.datafiles

# load data from files:
data = label = Uc = tuple( )

for i in range(len(datafiles)):
	d, l, p = read_datafile(datafiles[i])
	print(l + ': Uc = ' + str(p.Uc))
	data  += (d,)
	label += (l,)
	Uc    += (p.Uc,)

m = np.mean(Uc)
s = np.std(Uc)
print('Mean Uc = ' + str(m) + ' V')
print('StdDev Uc = ' + str(s) + ' V')
print('RSD = ' + str(np.abs(s/m*100)) + ' %')


